-- MySQL Script generated by MySQL Workbench
-- 04/08/17 00:22:58
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema db_stefanini
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema db_stefanini
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `db_stefanini` DEFAULT CHARACTER SET utf8 ;
USE `db_stefanini` ;

-- -----------------------------------------------------
-- Table `db_stefanini`.`tbf_funcionario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_stefanini`.`tbf_funcionario` (
  `tbf_id` INT NOT NULL AUTO_INCREMENT,
  `tbf_nome` VARCHAR(100) NOT NULL,
  `tbf_cpf` INT(11) NOT NULL,
  `tbf_endereco` VARCHAR(455) NOT NULL,
  `tbf_telefone` INT(15) NULL,
  PRIMARY KEY (`tbf_id`),
  UNIQUE INDEX `tbf_cpf_UNIQUE` (`tbf_cpf` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_stefanini`.`tbc_cargo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_stefanini`.`tbc_cargo` (
  `tbc_id` INT NOT NULL AUTO_INCREMENT,
  `tbc_cargo` VARCHAR(100) NOT NULL,
  `tbc_descricao` VARCHAR(455) NULL,
  `tbc_valorHora` DOUBLE NOT NULL,
  PRIMARY KEY (`tbc_id`),
  UNIQUE INDEX `tbc_cargo_UNIQUE` (`tbc_cargo` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_stefanini`.`tbe_empresa`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_stefanini`.`tbe_empresa` (
  `tbe_id` INT NOT NULL AUTO_INCREMENT,
  `tbe_nome_fantasia` VARCHAR(255) NOT NULL,
  `tbe_nome_empresarial` VARCHAR(255) NULL,
  `cnpj` INT(15) NOT NULL,
  PRIMARY KEY (`tbe_id`))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
